/**
 * Admin authentication.
 *
 * The dashboard is single-operator, so it uses one password rather than a user
 * table. That keeps the attack surface tiny, but it means the password itself
 * has to be handled properly:
 *
 *   - the plaintext password is never stored or logged; the environment holds
 *     a scrypt hash generated by `npm run admin:hash`;
 *   - verification is constant time;
 *   - the session cookie is a signed, expiring token - it carries no
 *     privileges of its own and cannot be forged without SERVER_SECRET;
 *   - sign-in attempts are rate limited.
 *
 * Even a fully compromised admin session cannot read a note: the dashboard
 * only ever queries aggregate counters, and the data simply is not there.
 */
import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

import { adminPasswordHash, isProduction, serverSecret } from './env';

export const ADMIN_COOKIE = 'shrednote_admin';
/** Sessions are short by design; the dashboard is not a place to linger. */
export const ADMIN_SESSION_SECONDS = 60 * 60 * 8;

const SCRYPT_KEYLEN = 64;
const SCRYPT_PARAMS = { N: 16384, r: 8, p: 1 } as const;

/**
 * Field separator for the stored hash.
 *
 * NOT '$', even though that is the conventional choice for password hash
 * strings. This value lives in an environment variable, and dotenv-style
 * loaders - including the one Next.js uses - perform variable expansion on
 * `$name` sequences even inside single quotes. A '$'-separated hash is
 * silently rewritten on load, and the admin password then never matches.
 *
 * '.' is outside the base64url alphabet, so it cannot collide with the salt or
 * the digest, and it has no meaning to any shell or env parser.
 */
const SEPARATOR = '.';

/** Produces the value stored in ADMIN_PASSWORD_HASH. */
export function hashAdminPassword(password: string): string {
  const salt = randomBytes(16);
  const derived = scryptSync(password, salt, SCRYPT_KEYLEN, { ...SCRYPT_PARAMS });
  return [
    'scrypt',
    SCRYPT_PARAMS.N,
    SCRYPT_PARAMS.r,
    SCRYPT_PARAMS.p,
    salt.toString('base64url'),
    derived.toString('base64url'),
  ].join(SEPARATOR);
}

/**
 * Constant-time verification against the configured hash.
 *
 * Returns false rather than throwing for every malformed input, so a
 * misconfigured deployment fails closed instead of 500-ing.
 */
export function verifyAdminPassword(password: string): boolean {
  const stored = adminPasswordHash();
  if (!stored) return false;

  const parts = stored.split(SEPARATOR);
  if (parts.length !== 6 || parts[0] !== 'scrypt') return false;

  const N = Number(parts[1]);
  const r = Number(parts[2]);
  const p = Number(parts[3]);
  if (!Number.isInteger(N) || !Number.isInteger(r) || !Number.isInteger(p)) return false;

  let expected: Buffer;
  try {
    expected = Buffer.from(parts[5]!, 'base64url');
  } catch {
    return false;
  }
  if (expected.length !== SCRYPT_KEYLEN) return false;

  const derived = scryptSync(password, Buffer.from(parts[4]!, 'base64url'), SCRYPT_KEYLEN, {
    N,
    r,
    p,
    // scrypt with N=16384, r=8 needs more than Node's default 32 MB limit.
    maxmem: 256 * 1024 * 1024,
  });

  return timingSafeEqual(derived, expected);
}

function sign(payload: string): string {
  return createHmac('sha256', serverSecret()).update(payload).digest('base64url');
}

/** Issues `<expiry>.<nonce>.<hmac>`. */
export function createAdminSession(now = Date.now()): { token: string; maxAge: number } {
  const expiresAt = Math.floor(now / 1000) + ADMIN_SESSION_SECONDS;
  const nonce = randomBytes(12).toString('base64url');
  const payload = `${expiresAt}.${nonce}`;
  return { token: `${payload}.${sign(payload)}`, maxAge: ADMIN_SESSION_SECONDS };
}

export function verifyAdminSession(token: string | undefined, now = Date.now()): boolean {
  if (!token) return false;
  const parts = token.split('.');
  if (parts.length !== 3) return false;

  const [expiresAt, nonce, signature] = parts as [string, string, string];
  const expected = Buffer.from(sign(`${expiresAt}.${nonce}`), 'utf8');
  const provided = Buffer.from(signature, 'utf8');
  if (expected.length !== provided.length) return false;
  if (!timingSafeEqual(expected, provided)) return false;

  const expiry = Number(expiresAt);
  return Number.isInteger(expiry) && expiry * 1000 > now;
}

export function adminCookieOptions(maxAge: number) {
  return {
    httpOnly: true,
    sameSite: 'strict' as const,
    secure: isProduction(),
    path: '/',
    maxAge,
  };
}

/** True when an admin password has been configured at all. */
export function isAdminConfigured(): boolean {
  return adminPasswordHash() !== null;
}
