import type { Metadata } from 'next';

import { PageShell } from '@/components/layout/PageShell';
import { site } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Privacy',
  description:
    'What ShredNote stores, what it cannot store, how long encrypted notes are kept, and the minimal logs we retain for abuse prevention. No accounts, no advertising trackers.',
  alternates: { canonical: '/privacy' },
};

const UPDATED = 'September 2026';

export default function PrivacyPage() {
  return (
    <PageShell
      eyebrow="Privacy"
      title="What we hold, and what we cannot."
      lead="Written to be read, not to be survived. If anything here is unclear, assume the least flattering reading and ask us to fix the wording."
    >
      <p className="!mt-0 text-[0.9375rem] text-faint">Last updated: {UPDATED}</p>

      <h2>The short version</h2>
      <ul>
        <li>No account, no email address, no sign-up.</li>
        <li>
          Your note is encrypted in your browser. We store ciphertext we cannot read and never
          intentionally store plaintext note contents.
        </li>
        <li>Encryption keys are never sent to us, so we cannot store them.</li>
        <li>Encrypted notes are deleted once read, or when they expire.</li>
        <li>No advertising trackers anywhere, and no analytics at all on note pages.</li>
      </ul>

      <h2>No account is required</h2>
      <p>
        ShredNote works without registration. We do not ask for your name, email address or phone
        number, and there is no profile associated with the notes you create. Two notes created from
        the same browser are not linked to each other in our database.
      </p>

      <h2>What we store for each note</h2>
      <p>A note record contains only:</p>
      <ul>
        <li>
          A random 22-character identifier with 128 bits of entropy, generated by a cryptographically
          secure random number generator.
        </li>
        <li>
          The encrypted message, the encrypted content key, and the non-secret values needed to
          decrypt with the right key (an initialisation vector, a salt, and a key-derivation
          iteration count).
        </li>
        <li>The creation time, the expiry time, and — once read — the time it was consumed.</li>
        <li>Whether a password was set, and a hash of a password proof. Never the password.</li>
        <li>
          The optional reference label, if the sender chose to add one. This is stored unencrypted
          by design so it can be shown before the note is opened; the interface says so clearly and
          warns against putting anything sensitive in it.
        </li>
        <li>The size of the ciphertext in bytes, used only for storage reporting.</li>
      </ul>

      <h2>What we do not store</h2>
      <ul>
        <li>
          <strong>Plaintext note contents.</strong> ShredNote does not intentionally store the
          readable text of any note. Encryption happens in your browser before anything is
          transmitted.
        </li>
        <li>
          <strong>Encryption keys.</strong> The key lives in the URL fragment — the part after the{' '}
          <code className="font-mono">#</code> — which browsers do not transmit. We never receive
          it, so we cannot keep it, hand it over, or lose it.
        </li>
        <li>
          <strong>Passwords.</strong> If you set one, your browser derives a proof of knowledge from
          it and sends only that. We store a hash of the proof, which cannot decrypt a note and
          cannot practically be reversed into your password.
        </li>
        <li>
          <strong>Recipient identity.</strong> We do not know who opened a note, only that it was
          opened.
        </li>
      </ul>

      <h2>How long encrypted notes are kept</h2>
      <p>
        An encrypted note is stored until it is read or until it expires, whichever comes first.
        Senders choose an expiry between one hour and {site.maxNoteAgeDays} days; the default keeps
        the link valid for up to {site.maxNoteAgeDays} days if nobody opens it. No note is stored
        beyond {site.maxNoteAgeDays} days under any setting.
      </p>
      <p>
        When a note is read, the ciphertext is erased in the same database operation that returns
        it. A small record with no message content remains briefly so that a second visit can be
        told the note is gone; that record is deleted by a scheduled cleanup job within seven days.
        Expired notes that were never read are deleted outright.
      </p>
      <p>
        Routine database backups, if taken, may briefly contain encrypted notes that have since been
        deleted. They contain no keys, so their contents remain unreadable.
      </p>

      <h2>Logs and abuse prevention</h2>
      <p>
        Running a free, anonymous service without any logging is not realistic — it would be trivial
        to flood. We keep the minimum needed to keep the service up:
      </p>
      <ul>
        <li>
          <strong>Rate limiting.</strong> Your IP address is converted into a keyed HMAC digest and
          used as a counter bucket. The raw address is not written to our database, and rotating our
          server secret makes existing digests meaningless.
        </li>
        <li>
          <strong>Application logs.</strong> We record events such as &ldquo;a note was
          created&rdquo; or &ldquo;a request was rate limited&rdquo;, with a fixed set of
          non-identifying fields. Our logging code physically refuses fields outside that list, so a
          note body or key cannot be logged by accident.
        </li>
        <li>
          <strong>Aggregate counters.</strong> Daily totals — notes created, read, expired — power
          an internal dashboard. They contain no note identifiers and cannot be traced to a person.
        </li>
      </ul>
      <p>
        <strong>We never log URL fragments.</strong> They cannot reach our servers in the first
        place, and nothing in our stack attempts to capture them from the client.
      </p>
      <p>
        Your hosting provider and ours may keep short-lived network-level logs as part of normal
        operation. Those are outside our application and typically record the IP address and the
        requested path — which, for a note, includes the note&rsquo;s identifier. They never contain
        the fragment, so such a log could at most reveal that a note existed or let someone destroy
        an unread one; it could never make a note readable. We keep provider logging to the minimum
        our platform allows.
      </p>

      <h2>Analytics and trackers</h2>
      <p>
        There is no advertising tracking on ShredNote, and no third-party scripts of any kind. Note
        creation pages and note reading pages carry no analytics whatsoever. If we ever add
        analytics to informational pages, it will be a privacy-friendly, cookie-free option that
        does not profile visitors, and this page will say so before it ships.
      </p>

      <h2>Cookies</h2>
      <p>
        The public product sets no cookies. The only cookie ShredNote can set is the session cookie
        for the site owner&rsquo;s admin dashboard, which is strictly necessary and never set for
        ordinary visitors.
      </p>

      <h2>Sharing your data</h2>
      <p>
        We do not sell or share note data, because we do not have anything readable to sell or
        share. If we were compelled by law to produce what we hold for a given note, we could
        produce only ciphertext and timestamps. We could not produce the message.
      </p>

      <h2>Honest limitations</h2>
      <p>
        ShredNote is not &ldquo;100% secure&rdquo; and no service that says so is telling you the
        truth. Specifically:
      </p>
      <ul>
        <li>Anyone who obtains the full link before your recipient can read the note.</li>
        <li>
          A compromised device on either end — malware, a malicious extension, someone looking at
          the screen — defeats any encryption.
        </li>
        <li>
          In-browser encryption requires trusting that the code we serve behaves as documented. That
          assumption is inherent to every tool of this kind.
        </li>
        <li>
          Once a recipient has read a note, what they do with it is beyond our reach. They can
          screenshot it.
        </li>
      </ul>

      <h2>Children</h2>
      <p>
        ShredNote is not directed at children and we do not knowingly collect information from
        anyone. Since the service collects no personal data at all, there is nothing to remove.
      </p>

      <h2>Changes</h2>
      <p>
        If this policy changes in a way that affects what we store or retain, we will update the
        date at the top and describe the change in plain language rather than quietly editing the
        text.
      </p>
    </PageShell>
  );
}
